source:       .
destination:  ./_site
markdown:     kramdown
kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
detach:       false
port:         9001
host:         127.0.0.1
baseurl:      "" # does not include hostname
